### ISSUE TITLE
Sublime SFTP Error

### ISSUE THREAD

**Issue by AnhellO** [Yelrado/sftp-config-hook#1]
After changing branch from GitHub Desktop:

> Sublime SFTP Error parsing sftp-config.json file: No JSON object could be decoded

The alert kept poping-up, until I closed Sublime, and deleted the sftp file (that was completely erased). Then I had to map my local repo to remote again, and generate a new sftp file (also, I had to delete the post-checkout file on the .git/hook/ folder) to get sublime back to work again.

:(

**Comment by AnhellO** [comment]
I think you can change between branches only from terminal, am I ok bro?

**Comment by AnhellO** [comment]
@Yelrado, definitelly. I'll close the issue :point_up: :smile:

**Comment by Yelrado** [comment]
Oh my, I didn't notice you created an issue for this. I'm sorry.

**Comment by Yelrado** [comment]
This has been resolved with this commit c23efaf92db142063469163b92cb32175f399613.
Documentation still needs to be updated.
